### ISSUE TITLE
ApplicationSecret value just says "[secret]" in output

### ISSUE THREAD

**Issue by jensbarthel** [pulumi/pulumi-azuread#233]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When creating an `ApplicationSecret`, there is no way to expose the secret value as an output for further processing.
In the context at hand, this secret is in fact supposed to be used by humans and therefore should be exposed as an output.

### Steps to reproduce
Creating an ApplicationSecret in a Stack with

```typescript
const applicationSecret = new azuread.ApplicationPassword("secretForSomeApplication", {
    applicationObjectId: someApplication.objectId,
    displayName: "User Onboarding Secret"
})
export const applicationSecretValue = applicationSecret.value
```

Expected: Should yield the secret value in the output
Actual: The output for the secret is
```shell
....
+ applicationSecretValue: "[secret]"
....
```

**Comment by pierskarsenbarg** [comment]
Hi @jensbarthel,

the `[secret]` is only masked within the screen output so that you don't accidentally display the secret in logging or similar.

You can access the secret through the CLI by running `pulumi stack output applicationSecretValue --show-secrets` or you can access them in other stacks by using the `getSecret()` method. More information can be found [in our docs](https://www.pulumi.com/docs/intro/concepts/secrets/).

**Comment by jensbarthel** [comment]
Ah, thank you for the swift clarification! :+1:

**Comment by pierskarsenbarg** [comment]
No problem. I'll close this issue.
